module.exports.eslintConfig = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'tsconfig.json',
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: ['@typescript-eslint', 'import', 'react', 'sort-imports-es6-autofix'],
  rules: {
    complexity: 'error',
    curly: 'warn',
    'default-case': 'warn',
    'eol-last': ['warn', 'always'],
    eqeqeq: ['error', 'always'],
    'new-parens': 'warn',
    'no-bitwise': 'error',
    'no-console': 'warn',
    'no-multiple-empty-lines': 'warn',
    'no-return-await': 'error',
    'no-useless-constructor': 'error',
    'no-var': 'warn',
    'prefer-const': 'warn',
    'prefer-spread': 'warn',
    'no-debugger': 'warn',
    'array-bracket-spacing': 'warn',
    'block-spacing': 'warn',
    'comma-spacing': 'warn',
    'computed-property-spacing': [2, 'never'],
    'no-mixed-spaces-and-tabs': 'warn',
    'no-spaced-func': 'warn',
    'no-trailing-spaces': 'warn',
    'space-before-blocks': 'warn',
    'arrow-spacing': 'warn',
    'generator-star-spacing': 'warn',
    'for-direction': 'warn',
    'sort-imports-es6-autofix/sort-imports-es6': [
      2,
      {
        ignoreCase: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
      },
    ],
    'valid-jsdoc': ['warn', { requireReturn: false }],
    'no-unused-vars': 'error',
    '@typescript-eslint/no-unused-vars': 'error',
    'react/jsx-uses-react': 'error',
    'react/jsx-uses-vars': 'error',
  },
};

module.exports.prettierConfig = {
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: false,
  printWidth: 150,
};
